-- coproc_soft_cpu_CPU.vhd

-- This file was auto-generated from intel_niosv_m_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 24.1 1077

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity coproc_soft_cpu_CPU is
	port (
		clk                               : in  std_logic                     := '0';             --                 clk.clk
		reset_reset                       : in  std_logic                     := '0';             --               reset.reset
		platform_irq_rx_irq               : in  std_logic_vector(15 downto 0) := (others => '0'); --     platform_irq_rx.irq
		ndm_reset_in_reset                : in  std_logic                     := '0';             --        ndm_reset_in.reset
		timer_sw_agent_address            : in  std_logic_vector(5 downto 0)  := (others => '0'); --      timer_sw_agent.address
		timer_sw_agent_byteenable         : in  std_logic_vector(3 downto 0)  := (others => '0'); --                    .byteenable
		timer_sw_agent_read               : in  std_logic                     := '0';             --                    .read
		timer_sw_agent_readdata           : out std_logic_vector(31 downto 0);                    --                    .readdata
		timer_sw_agent_write              : in  std_logic                     := '0';             --                    .write
		timer_sw_agent_writedata          : in  std_logic_vector(31 downto 0) := (others => '0'); --                    .writedata
		timer_sw_agent_waitrequest        : out std_logic;                                        --                    .waitrequest
		timer_sw_agent_readdatavalid      : out std_logic;                                        --                    .readdatavalid
		instruction_manager_readdata      : in  std_logic_vector(31 downto 0) := (others => '0'); -- instruction_manager.readdata
		instruction_manager_waitrequest   : in  std_logic                     := '0';             --                    .waitrequest
		instruction_manager_readdatavalid : in  std_logic                     := '0';             --                    .readdatavalid
		instruction_manager_response      : in  std_logic_vector(1 downto 0)  := (others => '0'); --                    .response
		instruction_manager_address       : out std_logic_vector(31 downto 0);                    --                    .address
		instruction_manager_read          : out std_logic;                                        --                    .read
		data_manager_readdata             : in  std_logic_vector(31 downto 0) := (others => '0'); --        data_manager.readdata
		data_manager_waitrequest          : in  std_logic                     := '0';             --                    .waitrequest
		data_manager_readdatavalid        : in  std_logic                     := '0';             --                    .readdatavalid
		data_manager_response             : in  std_logic_vector(1 downto 0)  := (others => '0'); --                    .response
		data_manager_address              : out std_logic_vector(31 downto 0);                    --                    .address
		data_manager_read                 : out std_logic;                                        --                    .read
		data_manager_write                : out std_logic;                                        --                    .write
		data_manager_writedata            : out std_logic_vector(31 downto 0);                    --                    .writedata
		data_manager_byteenable           : out std_logic_vector(3 downto 0);                     --                    .byteenable
		data_manager_writeresponsevalid   : in  std_logic                     := '0';             --                    .writeresponsevalid
		dm_agent_address                  : in  std_logic_vector(15 downto 0) := (others => '0'); --            dm_agent.address
		dm_agent_read                     : in  std_logic                     := '0';             --                    .read
		dm_agent_readdata                 : out std_logic_vector(31 downto 0);                    --                    .readdata
		dm_agent_write                    : in  std_logic                     := '0';             --                    .write
		dm_agent_writedata                : in  std_logic_vector(31 downto 0) := (others => '0'); --                    .writedata
		dm_agent_waitrequest              : out std_logic;                                        --                    .waitrequest
		dm_agent_readdatavalid            : out std_logic;                                        --                    .readdatavalid
		dbg_reset_out_reset               : out std_logic                                         --       dbg_reset_out.reset
	);
end entity coproc_soft_cpu_CPU;

architecture rtl of coproc_soft_cpu_CPU is
	component coproc_soft_cpu_CPU_hart is
		port (
			clk                   : in  std_logic                     := 'X';             -- clk
			reset                 : in  std_logic                     := 'X';             -- reset
			irq_plat_vec          : in  std_logic_vector(15 downto 0) := (others => 'X'); -- irq
			irq_debug             : in  std_logic                     := 'X';             -- irq
			irq_timer             : in  std_logic                     := 'X';             -- irq
			irq_sw                : in  std_logic                     := 'X';             -- irq
			instr_avl_rdata       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			instr_avl_waitrequest : in  std_logic                     := 'X';             -- waitrequest
			instr_avl_rdatavalid  : in  std_logic                     := 'X';             -- readdatavalid
			instr_avl_resp        : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- response
			instr_avl_addr        : out std_logic_vector(31 downto 0);                    -- address
			instr_avl_read        : out std_logic;                                        -- read
			data_avl_rdata        : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			data_avl_waitrequest  : in  std_logic                     := 'X';             -- waitrequest
			data_avl_rdatavalid   : in  std_logic                     := 'X';             -- readdatavalid
			data_avl_resp         : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- response
			data_avl_addr         : out std_logic_vector(31 downto 0);                    -- address
			data_avl_read         : out std_logic;                                        -- read
			data_avl_write        : out std_logic;                                        -- write
			data_avl_wdata        : out std_logic_vector(31 downto 0);                    -- writedata
			data_avl_byteen       : out std_logic_vector(3 downto 0);                     -- byteenable
			data_avl_wrespvalid   : in  std_logic                     := 'X'              -- writeresponsevalid
		);
	end component coproc_soft_cpu_CPU_hart;

	component coproc_soft_cpu_CPU_timer_module is
		port (
			clk                : in  std_logic                     := 'X';             -- clk
			reset              : in  std_logic                     := 'X';             -- reset
			hart_address       : in  std_logic_vector(5 downto 0)  := (others => 'X'); -- address
			hart_byteen        : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			hart_read          : in  std_logic                     := 'X';             -- read
			hart_readdata      : out std_logic_vector(31 downto 0);                    -- readdata
			hart_write         : in  std_logic                     := 'X';             -- write
			hart_writedata     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			hart_waitrequest   : out std_logic;                                        -- waitrequest
			hart_readdatavalid : out std_logic;                                        -- readdatavalid
			timer_irq          : out std_logic;                                        -- irq
			sw_irq             : out std_logic                                         -- irq
		);
	end component coproc_soft_cpu_CPU_timer_module;

	component coproc_soft_cpu_CPU_dbg_mod is
		port (
			clk                : in  std_logic                     := 'X';             -- clk
			reset              : in  std_logic                     := 'X';             -- reset
			hart_address       : in  std_logic_vector(15 downto 0) := (others => 'X'); -- address
			hart_read          : in  std_logic                     := 'X';             -- read
			hart_readdata      : out std_logic_vector(31 downto 0);                    -- readdata
			hart_write         : in  std_logic                     := 'X';             -- write
			hart_writedata     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			hart_waitrequest   : out std_logic;                                        -- waitrequest
			hart_readdatavalid : out std_logic;                                        -- readdatavalid
			dbg_irq            : out std_logic;                                        -- irq
			dbg_reset          : out std_logic                                         -- reset
		);
	end component coproc_soft_cpu_CPU_dbg_mod;

	component coproc_soft_cpu_CPU_irq_mapper is
		port (
			clk           : in  std_logic                    := 'X'; -- clk
			reset         : in  std_logic                    := 'X'; -- reset
			receiver0_irq : in  std_logic                    := 'X'; -- irq
			sender_irq    : out std_logic_vector(0 downto 0)         -- irq
		);
	end component coproc_soft_cpu_CPU_irq_mapper;

	component altera_reset_controller is
		generic (
			NUM_RESET_INPUTS          : integer := 6;
			OUTPUT_RESET_SYNC_EDGES   : string  := "deassert";
			SYNC_DEPTH                : integer := 2;
			RESET_REQUEST_PRESENT     : integer := 0;
			RESET_REQ_WAIT_TIME       : integer := 1;
			MIN_RST_ASSERTION_TIME    : integer := 3;
			RESET_REQ_EARLY_DSRT_TIME : integer := 1;
			USE_RESET_REQUEST_IN0     : integer := 0;
			USE_RESET_REQUEST_IN1     : integer := 0;
			USE_RESET_REQUEST_IN2     : integer := 0;
			USE_RESET_REQUEST_IN3     : integer := 0;
			USE_RESET_REQUEST_IN4     : integer := 0;
			USE_RESET_REQUEST_IN5     : integer := 0;
			USE_RESET_REQUEST_IN6     : integer := 0;
			USE_RESET_REQUEST_IN7     : integer := 0;
			USE_RESET_REQUEST_IN8     : integer := 0;
			USE_RESET_REQUEST_IN9     : integer := 0;
			USE_RESET_REQUEST_IN10    : integer := 0;
			USE_RESET_REQUEST_IN11    : integer := 0;
			USE_RESET_REQUEST_IN12    : integer := 0;
			USE_RESET_REQUEST_IN13    : integer := 0;
			USE_RESET_REQUEST_IN14    : integer := 0;
			USE_RESET_REQUEST_IN15    : integer := 0;
			ADAPT_RESET_REQUEST       : integer := 0
		);
		port (
			reset_in0      : in  std_logic := 'X'; -- reset
			reset_in1      : in  std_logic := 'X'; -- reset
			clk            : in  std_logic := 'X'; -- clk
			reset_out      : out std_logic;        -- reset
			reset_req      : out std_logic;        -- reset_req
			reset_req_in0  : in  std_logic := 'X'; -- reset_req
			reset_req_in1  : in  std_logic := 'X'; -- reset_req
			reset_in2      : in  std_logic := 'X'; -- reset
			reset_req_in2  : in  std_logic := 'X'; -- reset_req
			reset_in3      : in  std_logic := 'X'; -- reset
			reset_req_in3  : in  std_logic := 'X'; -- reset_req
			reset_in4      : in  std_logic := 'X'; -- reset
			reset_req_in4  : in  std_logic := 'X'; -- reset_req
			reset_in5      : in  std_logic := 'X'; -- reset
			reset_req_in5  : in  std_logic := 'X'; -- reset_req
			reset_in6      : in  std_logic := 'X'; -- reset
			reset_req_in6  : in  std_logic := 'X'; -- reset_req
			reset_in7      : in  std_logic := 'X'; -- reset
			reset_req_in7  : in  std_logic := 'X'; -- reset_req
			reset_in8      : in  std_logic := 'X'; -- reset
			reset_req_in8  : in  std_logic := 'X'; -- reset_req
			reset_in9      : in  std_logic := 'X'; -- reset
			reset_req_in9  : in  std_logic := 'X'; -- reset_req
			reset_in10     : in  std_logic := 'X'; -- reset
			reset_req_in10 : in  std_logic := 'X'; -- reset_req
			reset_in11     : in  std_logic := 'X'; -- reset
			reset_req_in11 : in  std_logic := 'X'; -- reset_req
			reset_in12     : in  std_logic := 'X'; -- reset
			reset_req_in12 : in  std_logic := 'X'; -- reset_req
			reset_in13     : in  std_logic := 'X'; -- reset
			reset_req_in13 : in  std_logic := 'X'; -- reset_req
			reset_in14     : in  std_logic := 'X'; -- reset
			reset_req_in14 : in  std_logic := 'X'; -- reset_req
			reset_in15     : in  std_logic := 'X'; -- reset
			reset_req_in15 : in  std_logic := 'X'  -- reset_req
		);
	end component altera_reset_controller;

	signal irq_mapper_receiver0_irq           : std_logic; -- dbg_mod:dbg_irq -> irq_mapper:receiver0_irq
	signal hart_debug_irq_rx_irq              : std_logic; -- irq_mapper:sender_irq -> hart:irq_debug
	signal irq_mapper_001_receiver0_irq       : std_logic; -- timer_module:timer_irq -> irq_mapper_001:receiver0_irq
	signal hart_timer_irq_rx_irq              : std_logic; -- irq_mapper_001:sender_irq -> hart:irq_timer
	signal irq_mapper_002_receiver0_irq       : std_logic; -- timer_module:sw_irq -> irq_mapper_002:receiver0_irq
	signal hart_sw_irq_rx_irq                 : std_logic; -- irq_mapper_002:sender_irq -> hart:irq_sw
	signal rst_controller_reset_out_reset     : std_logic; -- rst_controller:reset_out -> hart:reset
	signal rst_controller_001_reset_out_reset : std_logic; -- rst_controller_001:reset_out -> [irq_mapper:reset, irq_mapper_001:reset, irq_mapper_002:reset, timer_module:reset]

begin

	hart : component coproc_soft_cpu_CPU_hart
		port map (
			clk                   => clk,                               --             cpu_clk.clk
			reset                 => rst_controller_reset_out_reset,    --           cpu_reset.reset
			irq_plat_vec          => platform_irq_rx_irq,               --     platform_irq_rx.irq
			irq_debug             => hart_debug_irq_rx_irq,             --        debug_irq_rx.irq
			irq_timer             => hart_timer_irq_rx_irq,             --        timer_irq_rx.irq
			irq_sw                => hart_sw_irq_rx_irq,                --           sw_irq_rx.irq
			instr_avl_rdata       => instruction_manager_readdata,      -- instruction_manager.readdata
			instr_avl_waitrequest => instruction_manager_waitrequest,   --                    .waitrequest
			instr_avl_rdatavalid  => instruction_manager_readdatavalid, --                    .readdatavalid
			instr_avl_resp        => instruction_manager_response,      --                    .response
			instr_avl_addr        => instruction_manager_address,       --                    .address
			instr_avl_read        => instruction_manager_read,          --                    .read
			data_avl_rdata        => data_manager_readdata,             --        data_manager.readdata
			data_avl_waitrequest  => data_manager_waitrequest,          --                    .waitrequest
			data_avl_rdatavalid   => data_manager_readdatavalid,        --                    .readdatavalid
			data_avl_resp         => data_manager_response,             --                    .response
			data_avl_addr         => data_manager_address,              --                    .address
			data_avl_read         => data_manager_read,                 --                    .read
			data_avl_write        => data_manager_write,                --                    .write
			data_avl_wdata        => data_manager_writedata,            --                    .writedata
			data_avl_byteen       => data_manager_byteenable,           --                    .byteenable
			data_avl_wrespvalid   => data_manager_writeresponsevalid    --                    .writeresponsevalid
		);

	timer_module : component coproc_soft_cpu_CPU_timer_module
		port map (
			clk                => clk,                                --            clk.clk
			reset              => rst_controller_001_reset_out_reset, --          reset.reset
			hart_address       => timer_sw_agent_address,             -- timer_sw_agent.address
			hart_byteen        => timer_sw_agent_byteenable,          --               .byteenable
			hart_read          => timer_sw_agent_read,                --               .read
			hart_readdata      => timer_sw_agent_readdata,            --               .readdata
			hart_write         => timer_sw_agent_write,               --               .write
			hart_writedata     => timer_sw_agent_writedata,           --               .writedata
			hart_waitrequest   => timer_sw_agent_waitrequest,         --               .waitrequest
			hart_readdatavalid => timer_sw_agent_readdatavalid,       --               .readdatavalid
			timer_irq          => irq_mapper_001_receiver0_irq,       --      timer_irq.irq
			sw_irq             => irq_mapper_002_receiver0_irq        --         sw_irq.irq
		);

	dbg_mod : component coproc_soft_cpu_CPU_dbg_mod
		port map (
			clk                => clk,                      --           clk.clk
			reset              => reset_reset,              --         reset.reset
			hart_address       => dm_agent_address,         --      dm_agent.address
			hart_read          => dm_agent_read,            --              .read
			hart_readdata      => dm_agent_readdata,        --              .readdata
			hart_write         => dm_agent_write,           --              .write
			hart_writedata     => dm_agent_writedata,       --              .writedata
			hart_waitrequest   => dm_agent_waitrequest,     --              .waitrequest
			hart_readdatavalid => dm_agent_readdatavalid,   --              .readdatavalid
			dbg_irq            => irq_mapper_receiver0_irq, --       dbg_irq.irq
			dbg_reset          => dbg_reset_out_reset       -- dbg_reset_out.reset
		);

	irq_mapper : component coproc_soft_cpu_CPU_irq_mapper
		port map (
			clk           => clk,                                --       clk.clk
			reset         => rst_controller_001_reset_out_reset, -- clk_reset.reset
			receiver0_irq => irq_mapper_receiver0_irq,           -- receiver0.irq
			sender_irq(0) => hart_debug_irq_rx_irq               --    sender.irq
		);

	irq_mapper_001 : component coproc_soft_cpu_CPU_irq_mapper
		port map (
			clk           => clk,                                --       clk.clk
			reset         => rst_controller_001_reset_out_reset, -- clk_reset.reset
			receiver0_irq => irq_mapper_001_receiver0_irq,       -- receiver0.irq
			sender_irq(0) => hart_timer_irq_rx_irq               --    sender.irq
		);

	irq_mapper_002 : component coproc_soft_cpu_CPU_irq_mapper
		port map (
			clk           => clk,                                --       clk.clk
			reset         => rst_controller_001_reset_out_reset, -- clk_reset.reset
			receiver0_irq => irq_mapper_002_receiver0_irq,       -- receiver0.irq
			sender_irq(0) => hart_sw_irq_rx_irq                  --    sender.irq
		);

	rst_controller : component altera_reset_controller
		generic map (
			NUM_RESET_INPUTS          => 2,
			OUTPUT_RESET_SYNC_EDGES   => "none",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 0,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => reset_reset,                    -- reset_in0.reset
			reset_in1      => ndm_reset_in_reset,             -- reset_in1.reset
			clk            => open,                           --       clk.clk
			reset_out      => rst_controller_reset_out_reset, -- reset_out.reset
			reset_req      => open,                           -- (terminated)
			reset_req_in0  => '0',                            -- (terminated)
			reset_req_in1  => '0',                            -- (terminated)
			reset_in2      => '0',                            -- (terminated)
			reset_req_in2  => '0',                            -- (terminated)
			reset_in3      => '0',                            -- (terminated)
			reset_req_in3  => '0',                            -- (terminated)
			reset_in4      => '0',                            -- (terminated)
			reset_req_in4  => '0',                            -- (terminated)
			reset_in5      => '0',                            -- (terminated)
			reset_req_in5  => '0',                            -- (terminated)
			reset_in6      => '0',                            -- (terminated)
			reset_req_in6  => '0',                            -- (terminated)
			reset_in7      => '0',                            -- (terminated)
			reset_req_in7  => '0',                            -- (terminated)
			reset_in8      => '0',                            -- (terminated)
			reset_req_in8  => '0',                            -- (terminated)
			reset_in9      => '0',                            -- (terminated)
			reset_req_in9  => '0',                            -- (terminated)
			reset_in10     => '0',                            -- (terminated)
			reset_req_in10 => '0',                            -- (terminated)
			reset_in11     => '0',                            -- (terminated)
			reset_req_in11 => '0',                            -- (terminated)
			reset_in12     => '0',                            -- (terminated)
			reset_req_in12 => '0',                            -- (terminated)
			reset_in13     => '0',                            -- (terminated)
			reset_req_in13 => '0',                            -- (terminated)
			reset_in14     => '0',                            -- (terminated)
			reset_req_in14 => '0',                            -- (terminated)
			reset_in15     => '0',                            -- (terminated)
			reset_req_in15 => '0'                             -- (terminated)
		);

	rst_controller_001 : component altera_reset_controller
		generic map (
			NUM_RESET_INPUTS          => 2,
			OUTPUT_RESET_SYNC_EDGES   => "deassert",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 0,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => reset_reset,                        -- reset_in0.reset
			reset_in1      => ndm_reset_in_reset,                 -- reset_in1.reset
			clk            => clk,                                --       clk.clk
			reset_out      => rst_controller_001_reset_out_reset, -- reset_out.reset
			reset_req      => open,                               -- (terminated)
			reset_req_in0  => '0',                                -- (terminated)
			reset_req_in1  => '0',                                -- (terminated)
			reset_in2      => '0',                                -- (terminated)
			reset_req_in2  => '0',                                -- (terminated)
			reset_in3      => '0',                                -- (terminated)
			reset_req_in3  => '0',                                -- (terminated)
			reset_in4      => '0',                                -- (terminated)
			reset_req_in4  => '0',                                -- (terminated)
			reset_in5      => '0',                                -- (terminated)
			reset_req_in5  => '0',                                -- (terminated)
			reset_in6      => '0',                                -- (terminated)
			reset_req_in6  => '0',                                -- (terminated)
			reset_in7      => '0',                                -- (terminated)
			reset_req_in7  => '0',                                -- (terminated)
			reset_in8      => '0',                                -- (terminated)
			reset_req_in8  => '0',                                -- (terminated)
			reset_in9      => '0',                                -- (terminated)
			reset_req_in9  => '0',                                -- (terminated)
			reset_in10     => '0',                                -- (terminated)
			reset_req_in10 => '0',                                -- (terminated)
			reset_in11     => '0',                                -- (terminated)
			reset_req_in11 => '0',                                -- (terminated)
			reset_in12     => '0',                                -- (terminated)
			reset_req_in12 => '0',                                -- (terminated)
			reset_in13     => '0',                                -- (terminated)
			reset_req_in13 => '0',                                -- (terminated)
			reset_in14     => '0',                                -- (terminated)
			reset_req_in14 => '0',                                -- (terminated)
			reset_in15     => '0',                                -- (terminated)
			reset_req_in15 => '0'                                 -- (terminated)
		);

end architecture rtl; -- of coproc_soft_cpu_CPU
