-- coproc_soft_cpu_CPU.vhd

-- This file was auto-generated from intel_niosv_c_hw.tcl.  If you edit it your changes
-- will probably be lost.
-- 
-- Generated using ACDS version 24.1 1077

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity coproc_soft_cpu_CPU is
	port (
		clk                               : in  std_logic                     := '0';             --                 clk.clk
		reset_reset                       : in  std_logic                     := '0';             --               reset.reset
		instruction_manager_readdata      : in  std_logic_vector(31 downto 0) := (others => '0'); -- instruction_manager.readdata
		instruction_manager_waitrequest   : in  std_logic                     := '0';             --                    .waitrequest
		instruction_manager_readdatavalid : in  std_logic                     := '0';             --                    .readdatavalid
		instruction_manager_response      : in  std_logic_vector(1 downto 0)  := (others => '0'); --                    .response
		instruction_manager_address       : out std_logic_vector(31 downto 0);                    --                    .address
		instruction_manager_read          : out std_logic;                                        --                    .read
		data_manager_readdata             : in  std_logic_vector(31 downto 0) := (others => '0'); --        data_manager.readdata
		data_manager_waitrequest          : in  std_logic                     := '0';             --                    .waitrequest
		data_manager_readdatavalid        : in  std_logic                     := '0';             --                    .readdatavalid
		data_manager_response             : in  std_logic_vector(1 downto 0)  := (others => '0'); --                    .response
		data_manager_address              : out std_logic_vector(31 downto 0);                    --                    .address
		data_manager_read                 : out std_logic;                                        --                    .read
		data_manager_write                : out std_logic;                                        --                    .write
		data_manager_writedata            : out std_logic_vector(31 downto 0);                    --                    .writedata
		data_manager_byteenable           : out std_logic_vector(3 downto 0);                     --                    .byteenable
		data_manager_writeresponsevalid   : in  std_logic                     := '0'              --                    .writeresponsevalid
	);
end entity coproc_soft_cpu_CPU;

architecture rtl of coproc_soft_cpu_CPU is
	component coproc_soft_cpu_CPU_hart is
		port (
			clk                   : in  std_logic                     := 'X';             -- clk
			reset                 : in  std_logic                     := 'X';             -- reset
			instr_avl_rdata       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			instr_avl_waitrequest : in  std_logic                     := 'X';             -- waitrequest
			instr_avl_rdatavalid  : in  std_logic                     := 'X';             -- readdatavalid
			instr_avl_resp        : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- response
			instr_avl_addr        : out std_logic_vector(31 downto 0);                    -- address
			instr_avl_read        : out std_logic;                                        -- read
			data_avl_rdata        : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			data_avl_waitrequest  : in  std_logic                     := 'X';             -- waitrequest
			data_avl_rdatavalid   : in  std_logic                     := 'X';             -- readdatavalid
			data_avl_resp         : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- response
			data_avl_addr         : out std_logic_vector(31 downto 0);                    -- address
			data_avl_read         : out std_logic;                                        -- read
			data_avl_write        : out std_logic;                                        -- write
			data_avl_wdata        : out std_logic_vector(31 downto 0);                    -- writedata
			data_avl_byteen       : out std_logic_vector(3 downto 0);                     -- byteenable
			data_avl_wrespvalid   : in  std_logic                     := 'X'              -- writeresponsevalid
		);
	end component coproc_soft_cpu_CPU_hart;

begin

	hart : component coproc_soft_cpu_CPU_hart
		port map (
			clk                   => clk,                               --             cpu_clk.clk
			reset                 => reset_reset,                       --           cpu_reset.reset
			instr_avl_rdata       => instruction_manager_readdata,      -- instruction_manager.readdata
			instr_avl_waitrequest => instruction_manager_waitrequest,   --                    .waitrequest
			instr_avl_rdatavalid  => instruction_manager_readdatavalid, --                    .readdatavalid
			instr_avl_resp        => instruction_manager_response,      --                    .response
			instr_avl_addr        => instruction_manager_address,       --                    .address
			instr_avl_read        => instruction_manager_read,          --                    .read
			data_avl_rdata        => data_manager_readdata,             --        data_manager.readdata
			data_avl_waitrequest  => data_manager_waitrequest,          --                    .waitrequest
			data_avl_rdatavalid   => data_manager_readdatavalid,        --                    .readdatavalid
			data_avl_resp         => data_manager_response,             --                    .response
			data_avl_addr         => data_manager_address,              --                    .address
			data_avl_read         => data_manager_read,                 --                    .read
			data_avl_write        => data_manager_write,                --                    .write
			data_avl_wdata        => data_manager_writedata,            --                    .writedata
			data_avl_byteen       => data_manager_byteenable,           --                    .byteenable
			data_avl_wrespvalid   => data_manager_writeresponsevalid    --                    .writeresponsevalid
		);

end architecture rtl; -- of coproc_soft_cpu_CPU
